### PR TITLE
Add better ping fail message

### PR DESCRIPTION
**Pull request by randomairborne**
This PR improves the failure message for the ping command

### CODE REVIEW

**Review by tazz4843 — CHANGES_REQUESTED** [review]
Way too prone to other languages breaking (don't be Anglocentric). Use entirely new strings if you need to in the translation files.

**Comment by randomairborne** [comment]
i did add some new strings. There isn’t a great way to do this without the actual translators getting involved and helping actually write the messages, using an auto translator for long strings is somewhat sketch

**Comment by tazz4843** [comment]
Can't merge this then, screws with other languages too much.

**Comment by randomairborne** [comment]
What other options do you propose? The way it's done now is very messy.

**Comment by randomairborne** [comment]
This decision also makes it pretty impossible to ever change formatting on a message, as you need all of the translators to update along in the same PR.

**Pull request closed without merging**
